sudo: required

language: python

cache:
  directories:
    - src/game/.buildozer

services:
  - docker

before_install:
  - docker pull totaki/rock-band-tour

before_script:
  - cd src/game
  - mkdir .buildozer && chmod 777 .buildozer
  - mkdir bin && chmod 777 bin

script:
  - docker run --rm -v $PWD:/home/user/hostcwd totaki/rock-band-tour android release
